language: node_js
node_js:
    - 9
cache:
    directories:
        - node_modules
script:
    - yarn test
after_script:
    - yarn coveralls
after_success:
    - chmod +x .travis/publish.sh
    - .travis/publish.sh
