language: node_js
node_js:
    - 9
cache:
    directories:
        - node_modules
script:
    - yarn test
after_script:
    - yarn coveralls
deploy:
    provider: script
    script: sh .travis/publish.sh
    skip_cleanup: true
    on:
        branch: master
